(let ((quicklisp-init (merge-pathnames "quicklisp/setup.lisp" (user-homedir-pathname))))
  (when (probe-file quicklisp-init)
    (load quicklisp-init)))
(ql:quickload "alexandria")
(ql:quickload "series")
(ql:quickload "fold")
(ql:quickload "named-let")
(ql:quickload "function")

(require :asdf)
(push (truename ".") asdf:*central-registry*)
(asdf:load-system :clrhack)

(let ((tests '(("test-advanced.lisp" . "AdvancedTest")
               ("test-church.lisp" . "ChurchTest")
               ("test-closure.lisp" . "ClosureTest")
               ("test-fib.lisp" . "FibBenchmark")
               ("test-hello.lisp" . "HelloWorld")
               ("test-mutability.lisp" . "MutabilityTest")
               ("test-nboyer.lisp" . "NBoyerBenchmark")
               ("test-scoping.lisp" . "ScopingTests")
               ("test-tak.lisp" . "TakBenchmark")
               ("test-toplevel.lisp" . "TopLevelTest")
               ("test-complex.lisp" . "ComplexScopingTest")
               ("bank-test.lisp" . "BankTest")
               ("tail-test.lisp" . "TailTest"))))
  (dolist (test tests)
    (let ((file (car test))
          (target (cdr test)))
      (format t "~%--- Compiling ~A to ~A ---~%" file target)
      (clrhack:compile-file file :output-file target))))

(sb-ext:exit)
