(let ((quicklisp-init (merge-pathnames "quicklisp/setup.lisp" (user-homedir-pathname))))
  (when (probe-file quicklisp-init)
    (load quicklisp-init)))
(ql:quickload "alexandria")
(ql:quickload "series")
(ql:quickload "fold")
(ql:quickload "named-let")
(ql:quickload "function")

(require :asdf)
(push (truename ".") asdf:*central-registry*)
(asdf:load-system :clrhack)

(let ((tests '(
               ("test-advanced.lisp" . "AdvancedTest")
               ;; ("test-aux.lisp" . "AuxTest")
               ("bank-test.lisp" . "BankTest")
               ("test-block.lisp" . "BlockTest")
               ("test-catch.lisp" . "CatchTest")
               ("test-church.lisp" . "ChurchTest")
               ("test-closure.lisp" . "ClosureTest")
               ("test-complex.lisp" . "ComplexScopingTest")
               ;; ("test-dderiv.lisp" . "DderivBenchmark")
               ;; ("test-deriv.lisp" . "DerivBenchmark")
               ;; ("test-div2.lisp" . "Div2Benchmark")
               ;; ("test-ctak.lisp" . "CtakBenchmark")
               ("test-fib.lisp" . "FibBenchmark")
               ("test-flet.lisp" . "FletTest")
               ("test-hello.lisp" . "HelloWorld")
               ("test-interop.lisp" . "InteropTest")
               ;; ("test-javadot.lisp" . "JavadotTest")
               ;; ("test-key.lisp" . "KeyTest")
               ("test-labels.lisp" . "LabelsTest")
               ("test-letrec.lisp" . "LetRecTest")
               ;; ("test-ltak.lisp" . "LtakBenchmark")
               ("test-macro.lisp" . "MacroTest")
               ("test-mutability.lisp" . "MutabilityTest")
               ("test-nboyer.lisp" . "NBoyerBenchmark")
               ("Tests/puzzle-test.lisp" . "PuzzleBenchmark")
               ("test-scoping.lisp" . "ScopingTests")
               ;; ("test-stak.lisp" . "StakBenchmark")
               ("test-tagbody.lisp" . "TagbodyTest")
               ("test-tak.lisp" . "TakBenchmark")
               ("test-toplevel.lisp" . "TopLevelTest")
               ;; ("test-triang.lisp" . "TriangBenchmark")
               ("test-uwp.lisp" . "UwpTest"))))

  (dolist (test tests)
    (let ((file (car test))
          (target (cdr test)))
      (format t "~%--- Compiling ~A to ~A ---~%" file target)
      (clrhack:compile-file file :output-file target))))

(sb-ext:exit)
