(in-package "CLRHACK")

(compile-and-run
 '(let ((zero (lambda (f) (lambda (x) x)))
        (succ (lambda (n) (lambda (f) (lambda (x) (f ((n f) x))))))
        (add  (lambda (m n) (lambda (f) (lambda (x) ((m f) ((n f) x))))))
        (mul  (lambda (m n) (lambda (f) (lambda (x) ((m (n f)) x))))))
    (let ((one (succ zero)))
      (let ((two (succ one))
            (three (succ (succ one))))
        (let ((five (add two three))
              (six (mul two three)))
          (let ((tick (lambda (ignored) (%write-line "tick"))))
            (%write-line "Computing 2 + 3 ticks:")
            ((five tick) nil)
            (%write-line "Computing 2 * 3 ticks:")
            ((six tick) nil))))))
 "ChurchTest")