(defun test-key (a &key b (c 10) (d 20 d-p))
  (print a)
  (print b)
  (print c)
  (print d)
  (print d-p))

(defun test-key-ref (a &key (b (+ a 1)))
  (print a)
  (print b))

(defun main ()
  (print "--- test-key 1 ---")
  (test-key 1)
  (print "--- test-key 1 :b 2 ---")
  (test-key 1 :b 2)
  (print "--- test-key 1 :c 3 ---")
  (test-key 1 :c 3)
  (print "--- test-key 1 :d 4 ---")
  (test-key 1 :d 4)
  (print "--- test-key 1 :b 2 :c 3 :d 4 ---")
  (test-key 1 :b 2 :c 3 :d 4)
  (print "--- test-key 1 :d 4 :b 2 ---")
  (test-key 1 :d 4 :b 2)

  (print "--- test-key-ref 5 ---")
  (test-key-ref 5)
  (print "--- test-key-ref 5 :b 10 ---")
  (test-key-ref 5 :b 10)

  (print "--- lambda test ---")
  (let ((f (lambda (x &key (y (+ x 1)))
             (print x)
             (print y))))
    (funcall f 10)
    (funcall f 10 :y 20)))

(main)
