(in-package "CLRHACK")

(let ((a "outer-a"))
  (let ((f (lambda (b)
             (let ((c "inner-c"))
               (let ((g (lambda (d)
                          (%write-line "Inside g:")
                          (%write-line a)
                          (%write-line b)
                          (%write-line c)
                          (%write-line d)
                          (setq a "a-mutated-by-g")
                          (setq b "b-mutated-by-g")
                          (setq c "c-mutated-by-g")
                          nil)))
                 (%write-line "Before calling g:")
                 (%write-line a)
                 (%write-line b)
                 (%write-line c)
                 (g "param-d")
                 (%write-line "After calling g:")
                 (%write-line a)
                 (%write-line b)
                 (%write-line c)
                 nil)))))
    (%write-line "Before calling f:")
    (%write-line a)
    (f "param-b")
    (%write-line "After calling f:")
    (%write-line a)))
