(in-package "CLRHACK")

(let ((a "outer-a"))
  (let ((f (lambda (b)
             (let ((c "inner-c"))
               (let ((g (lambda (d)
                          (print "Inside g:")
                          (print a)
                          (print b)
                          (print c)
                          (print d)
                          (setq a "a-mutated-by-g")
                          (setq b "b-mutated-by-g")
                          (setq c "c-mutated-by-g")
                          nil)))
                 (print "Before calling g:")
                 (print a)
                 (print b)
                 (print c)
                 (g "param-d")
                 (print "After calling g:")
                 (print a)
                 (print b)
                 (print c)
                 nil)))))
    (print "Before calling f:")
    (print a)
    (f "param-b")
    (print "After calling f:")
    (print a)))
