(in-package "CLRHACK")

(defvar *puzzle-size* 511)
(defvar *puzzle-classmax* 3)
(defvar *puzzle-typemax* 12)
(defvar *puzzle-dee* 8)

(defvar *iii* 0)
(defvar *kount* 0)

(defvar *p-piececount* (make-array 4))
(defvar *p-class* (make-array 13))
(defvar *p-piecemax* (make-array 13))
(defvar *p-puzzl* (make-array 512))
(defvar *p-p* (make-array 6656)) ; 13 * 512

(defun p-fit (i j)
  (let ((end (aref *p-piecemax* i))
        (k 0)
        (result nil))
    (tagbody
     loop
       (if (< end k)
           (progn (setq result t) (go done))
           nil)
       (if (aref *p-p* (+ (* i 512) k))
           (let ((idx (+ j k)))
             (if (< *puzzle-size* idx)
                 (progn (setq result nil) (go done))
                 (if (aref *p-puzzl* idx)
                     (progn (setq result nil) (go done))
                     nil)))
           nil)
       (setq k (+ k 1))
       (go loop)
     done)
    result))

(defun p-place (i j)
  (let ((end (aref *p-piecemax* i))
        (k 0))
    (tagbody
     loop
       (if (< end k)
           (go done)
           nil)
       (if (aref *p-p* (+ (* i 512) k))
           (let ((idx (+ j k)))
             (if (< *puzzle-size* idx)
                 nil
                 (aset *p-puzzl* idx t)))
           nil)
       (setq k (+ k 1))
       (go loop)
     done)
    (let* ((class (aref *p-class* i))
           (count (aref *p-piececount* class)))
      (aset *p-piececount* class (- count 1)))
    (let ((k2 j)
          (result nil))
      (tagbody
       loop2
         (if (< *puzzle-size* k2)
             (progn (setq result nil) (go done2))
             (if (not (aref *p-puzzl* k2))
                 (progn (setq result k2) (go done2))
                 nil))
         (setq k2 (+ k2 1))
         (go loop2)
       done2)
      result)))

(defun p-remove (i j)
  (let ((end (aref *p-piecemax* i))
        (k 0))
    (tagbody
     loop
       (if (< end k)
           (go done)
           nil)
       (if (aref *p-p* (+ (* i 512) k))
           (let ((idx (+ j k)))
             (if (< *puzzle-size* idx)
                 nil
                 (aset *p-puzzl* idx nil)))
           nil)
       (setq k (+ k 1))
       (go loop)
     done)
    (let* ((class (aref *p-class* i))
           (count (aref *p-piececount* class)))
      (aset *p-piececount* class (+ count 1)))))

(defun p-trial (j)
  (let ((i 0)
        (result nil))
    (tagbody
     loop
       (if (< *puzzle-typemax* i)
           (progn (setq *kount* (+ *kount* 1)) (setq result nil) (go done))
           (let* ((class (aref *p-class* i))
                  (count (aref *p-piececount* class)))
             (if (not (eq count 0))
                 (if (p-fit i j)
                     (let ((n (p-place i j)))
                       (if (or (null n) (p-trial n))
                           (progn (setq *kount* (+ *kount* 1)) (setq result t) (go done))
                           (progn (p-remove i j) (setq i (+ i 1)) (go loop))))
                     (progn (setq i (+ i 1)) (go loop)))
                 (progn (setq i (+ i 1)) (go loop)))))
     done)
    result))

(defun p-define-piece (icom iclass x y z)
  (let ((i 0))
    (tagbody
     loop-i
       (if (< x i)
           (go done-i)
           nil)
       (let ((j 0))
         (tagbody
          loop-j
            (if (< y j)
                (go done-j)
                nil)
            (let ((k 0))
              (tagbody
               loop-k
                 (if (< z k)
                     (go done-k)
                     nil)
                 (let ((index (+ i (* *puzzle-dee* (+ j (* *puzzle-dee* k))))))
                   (aset *p-p* (+ (* icom 512) index) t))
                 (setq k (+ k 1))
                 (go loop-k)
               done-k))
            (setq j (+ j 1))
            (go loop-j)
          done-j))
       (setq i (+ i 1))
       (go loop-i)
     done-i))
  (aset *p-class* icom iclass)
  (let ((index (+ x (* *puzzle-dee* (+ y (* *puzzle-dee* z))))))
    (aset *p-piecemax* icom index))
  (if (< *iii* *puzzle-typemax*)
      (setq *iii* (+ *iii* 1))
      0))

(defun puzzle-start ()
  (setq *kount* 0)
  (let ((i 0))
    (tagbody
     loop
       (if (< *puzzle-size* i)
           (go done)
           nil)
       (aset *p-puzzl* i t)
       (setq i (+ i 1))
       (go loop)
     done))
  (let ((i 1))
    (tagbody
     loop-i
       (if (< 5 i)
           (go done-i)
           nil)
       (let ((j 1))
         (tagbody
          loop-j
            (if (< 5 j)
                (go done-j)
                nil)
            (let ((k 1))
              (tagbody
               loop-k
                 (if (< 5 k)
                     (go done-k)
                     nil)
                 (let ((idx (+ k (* 8 (+ j (* 8 i))))))
                   (aset *p-puzzl* idx nil))
                 (setq k (+ k 1))
                 (go loop-k)
               done-k))
            (setq j (+ j 1))
            (go loop-j)
          done-j))
       (setq i (+ i 1))
       (go loop-i)
     done-i))
  (aset *p-piececount* 0 13)
  (aset *p-piececount* 1 3)
  (aset *p-piececount* 2 1)
  (aset *p-piececount* 3 1)
  (let ((i 0))
    (tagbody
     loop-i2
       (if (< *puzzle-size* i)
           (go done-i2)
           nil)
       (let ((j 0))
         (tagbody
          loop-j2
            (if (< *puzzle-typemax* j)
                (go done-j2)
                nil)
            (aset *p-p* (+ (* j 512) i) nil)
            (setq j (+ j 1))
            (go loop-j2)
          done-j2))
       (setq i (+ i 1))
       (go loop-i2)
     done-i2))
  (setq *iii* 0)
  (p-define-piece 0 0 3 1 0)
  (p-define-piece 1 0 1 0 3)
  (p-define-piece 2 0 0 3 1)
  (p-define-piece 3 0 1 3 0)
  (p-define-piece 4 0 3 0 1)
  (p-define-piece 5 0 0 1 3)
  (p-define-piece 6 1 2 0 0)
  (p-define-piece 7 1 0 2 0)
  (p-define-piece 8 1 0 0 2)
  (p-define-piece 9 2 1 1 0)
  (p-define-piece 10 2 1 0 1)
  (p-define-piece 11 2 0 1 1)
  (p-define-piece 12 3 1 1 1)
  (let ((m (+ 1 (* *puzzle-dee* (+ 1 *puzzle-dee*)))))
    (if (p-fit 0 m)
        (let ((n (p-place 0 m)))
          (if (p-trial n)
              (progn (print "Kount:") (print *kount*) *kount*)
              (print "Puzzle failed")))
        (print "Puzzle setup failed"))))

(defun main ()
  (puzzle-start))

(main)
