(in-package "CLRHACK")

(progn
  (defun test-optional (a &optional (b "default-b") (c "default-c" c-p))
    (print "test-optional")
    (print a)
    (print b)
    (print c)
    (print c-p))

  (defun test-rest (a &rest args)
    (print "test-rest")
    (print a)
    (print args))

  (defun test-mixed (a &optional (b 10) &rest args)
    (print "test-mixed")
    (print a)
    (print b)
    (print args))

  (defun test-key (a &key b (c 10) (d 20 d-p))
    (print "test-key")
    (print a)
    (print b)
    (print c)
    (print d)
    (print d-p))

  (defun main ()
    (print "--- optional 1 ---")
    (test-optional "A")
    (print "--- optional 2 ---")
    (test-optional "A" "B")
    (print "--- optional 3 ---")
    (test-optional "A" "B" "C")

    (print "--- rest 0 ---")
    (test-rest "A")
    (print "--- rest 1 ---")
    (test-rest "A" "B")
    (print "--- rest 2 ---")
    (test-rest "A" "B" "C")

    (print "--- mixed 1 ---")
    (test-mixed 1)
    (print "--- mixed 2 ---")
    (test-mixed 1 2)
    (print "--- mixed 3 ---")
    (test-mixed 1 2 3 4)

    (print "--- key 1 ---")
    (test-key 1)
    (print "--- key 2 ---")
    (test-key 1 :b 2)
    (print "--- key 3 ---")
    (test-key 1 :c 3 :b 4)
    (print "--- key 4 ---")
    (test-key 1 :d 40)

    (print "--- key odd error test ---")
    ;; This should crash with "Odd number of keyword arguments"
    ;; (test-key 1 :b)
    )

  (main)

  (print "--- lambda test ---")
  (let ((f (lambda (x &optional (y "default-y") &rest z)
             (print "lambda")
             (print x)
             (print y)
             (print z))))
    (print "lambda 1")
    (funcall f 1)
    (print "lambda 2")
    (funcall f 1 2)
    (print "lambda 3")
    (funcall f 1 2 3 4))

  (print "--- lambda key test ---")
  (let ((f (lambda (x &key (y 100) (z 200 z-p))
             (print "lambda-key")
             (print x)
             (print y)
             (print z)
             (print z-p))))
    (print "lambda-key 1")
    (funcall f 1)
    (print "lambda-key 2")
    (funcall f 1 :y 2)
    (print "lambda-key 3")
    (funcall f 1 :z 3 :y 4)))
