<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <Target Name="CompileIL" BeforeTargets="BeforeBuild" Condition="Exists('Hello.il')">
    <Exec Command="ilasm /dll /output:HelloLisp.dll Hello.il" Condition="'$(OS)' == 'Windows_NT'" />
    <Exec Command="ilasm /dll /output:HelloLisp.dll Hello.il" Condition="'$(OS)' != 'Windows_NT'" />
  </Target>

  <ItemGroup>
    <Reference Include="HelloLisp">
      <HintPath>HelloLisp.dll</HintPath>
    </Reference>
    <ProjectReference Include="..\LispBase\LispBase.csproj" />
    <ProjectReference Include="..\CLSymbols\CLSymbols.csproj" />
  </ItemGroup>

</Project>
