using System;
using Xunit;
using Lisp;

namespace CLRHack.Tests
{
    public class ClosureInvokeTests
    {
        // Simulates a closure generated by the IL generator for a lambda with 1 parameter.
        // It implements the actual logic in Invoke(arg0) and throws for all other stubs.
        private class GeneratedClosureMock : Closure
        {
            public override object Invoke() => throw new WrongNumberOfArgumentsException(1, 0);
            
            public override object Invoke(object arg0) => arg0; // The actual implementation
            
            public override object Invoke(object arg0, object arg1) => throw new WrongNumberOfArgumentsException(1, 2);
            
            public override object Invoke(object arg0, object arg1, object arg2) => throw new WrongNumberOfArgumentsException(1, 3);
            
            public override object Invoke(object arg0, object arg1, object arg2, object arg3) => throw new WrongNumberOfArgumentsException(1, 4);
            
            public override object Invoke(object arg0, object arg1, object arg2, object arg3, object arg4) => throw new WrongNumberOfArgumentsException(1, 5);
            
            public override object Invoke(object arg0, object arg1, object arg2, object arg3, object arg4, object arg5) => throw new WrongNumberOfArgumentsException(1, 6);
            
            public override object Invoke(object arg0, object arg1, object arg2, object arg3, object arg4, object arg5, object arg6) => throw new WrongNumberOfArgumentsException(1, 7);
            
            public override object Invoke(object arg0, object arg1, object arg2, object arg3, object arg4, object arg5, object arg6, object arg7) => throw new WrongNumberOfArgumentsException(1, 8);
        }

        [Fact]
        public void Closure_InvokeWithWrongArguments_ThrowsWrongNumberOfArgumentsException()
        {
            Closure closure = new GeneratedClosureMock();

            // Correct number of arguments doesn't throw
            var result = closure.Invoke("test");
            Assert.Equal("test", result);

            // Too few arguments throws
            var ex1 = Assert.Throws<WrongNumberOfArgumentsException>(() => closure.Invoke());
            Assert.Equal(1, ex1.Expected);
            Assert.Equal(0, ex1.Provided);

            // Too many arguments throws
            var ex2 = Assert.Throws<WrongNumberOfArgumentsException>(() => closure.Invoke("arg1", "arg2"));
            Assert.Equal(1, ex2.Expected);
            Assert.Equal(2, ex2.Provided);
        }
    }
}
