using System;
using Xunit;
using Lisp;

namespace CLRHack.Tests
{
    public class ClosureInvokeTests
    {
        // Simulates a closure generated by the IL generator for a lambda with 1 parameter.
        // It implements the actual logic in Invoke(arg0) and throws for all other stubs.
        private class GeneratedClosureMock : Closure
        {
            public override object Invoke() => throw new WrongNumberOfArgumentsException(1, 0);
            
            public override object Invoke(object arg0) => arg0; // The actual implementation
            
            public override object Invoke(object arg0, object arg1) => throw new WrongNumberOfArgumentsException(1, 2);
            
            public override object Invoke(object arg0, object arg1, object arg2) => throw new WrongNumberOfArgumentsException(1, 3);
            
            public override object Invoke(object arg0, object arg1, object arg2, object arg3) => throw new WrongNumberOfArgumentsException(1, 4);
            
            public override object Invoke(object arg0, object arg1, object arg2, object arg3, object arg4) => throw new WrongNumberOfArgumentsException(1, 5);
            
            public override object Invoke(object arg0, object arg1, object arg2, object arg3, object arg4, object arg5) => throw new WrongNumberOfArgumentsException(1, 6);
            
            public override object Invoke(object arg0, object arg1, object arg2, object arg3, object arg4, object arg5, object arg6) => throw new WrongNumberOfArgumentsException(1, 7);
            
            public override object Invoke(object arg0, object arg1, object arg2, object arg3, object arg4, object arg5, object arg6, object arg7) => throw new WrongNumberOfArgumentsException(1, 8);

            public override object Invoke(object arg0, object arg1, object arg2, object arg3, object arg4, object arg5, object arg6, object arg7, object arg8) => throw new WrongNumberOfArgumentsException(1, 9);

            public override object Invoke(object arg0, object arg1, object arg2, object arg3, object arg4, object arg5, object arg6, object arg7, object arg8, object arg9) => throw new WrongNumberOfArgumentsException(1, 10);

            public override object Invoke(object arg0, object arg1, object arg2, object arg3, object arg4, object arg5, object arg6, object arg7, object arg8, object arg9, object arg10) => throw new WrongNumberOfArgumentsException(1, 11);

            public override object Invoke(object arg0, object arg1, object arg2, object arg3, object arg4, object arg5, object arg6, object arg7, object arg8, object arg9, object arg10, object arg11) => throw new WrongNumberOfArgumentsException(1, 12);

            public override object Invoke(object arg0, object arg1, object arg2, object arg3, object arg4, object arg5, object arg6, object arg7, object arg8, object arg9, object arg10, object arg11, object arg12) => throw new WrongNumberOfArgumentsException(1, 13);

            public override object Invoke(object arg0, object arg1, object arg2, object arg3, object arg4, object arg5, object arg6, object arg7, object arg8, object arg9, object arg10, object arg11, object arg12, object arg13) => throw new WrongNumberOfArgumentsException(1, 14);

            public override object Invoke(object arg0, object arg1, object arg2, object arg3, object arg4, object arg5, object arg6, object arg7, object arg8, object arg9, object arg10, object arg11, object arg12, object arg13, object arg14) => throw new WrongNumberOfArgumentsException(1, 15);

            public override object Invoke(object arg0, object arg1, object arg2, object arg3, object arg4, object arg5, object arg6, object arg7, object arg8, object arg9, object arg10, object arg11, object arg12, object arg13, object arg14, object arg15) => throw new WrongNumberOfArgumentsException(1, 16);

            public override object Invoke(object arg0, object arg1, object arg2, object arg3, object arg4, object arg5, object arg6, object arg7, object arg8, object arg9, object arg10, object arg11, object arg12, object arg13, object arg14, object arg15, object arg16) => throw new WrongNumberOfArgumentsException(1, 17);

            public override object Invoke(object arg0, object arg1, object arg2, object arg3, object arg4, object arg5, object arg6, object arg7, object arg8, object arg9, object arg10, object arg11, object arg12, object arg13, object arg14, object arg15, object arg16, object arg17) => throw new WrongNumberOfArgumentsException(1, 18);

            public override object Invoke(object arg0, object arg1, object arg2, object arg3, object arg4, object arg5, object arg6, object arg7, object arg8, object arg9, object arg10, object arg11, object arg12, object arg13, object arg14, object arg15, object arg16, object arg17, object arg18) => throw new WrongNumberOfArgumentsException(1, 19);

            public override object Invoke(object arg0, object arg1, object arg2, object arg3, object arg4, object arg5, object arg6, object arg7, object arg8, object arg9, object arg10, object arg11, object arg12, object arg13, object arg14, object arg15, object arg16, object arg17, object arg18, object arg19) => throw new WrongNumberOfArgumentsException(1, 20);

            public override object Invoke(object arg0, object arg1, object arg2, object arg3, object arg4, object arg5, object arg6, object arg7, object arg8, object arg9, object arg10, object arg11, object arg12, object arg13, object arg14, object arg15, object arg16, object arg17, object arg18, object arg19, object arg20) => throw new WrongNumberOfArgumentsException(1, 21);

            public override object Invoke(object arg0, object arg1, object arg2, object arg3, object arg4, object arg5, object arg6, object arg7, object arg8, object arg9, object arg10, object arg11, object arg12, object arg13, object arg14, object arg15, object arg16, object arg17, object arg18, object arg19, object arg20, object arg21) => throw new WrongNumberOfArgumentsException(1, 22);

            public override object Invoke(object arg0, object arg1, object arg2, object arg3, object arg4, object arg5, object arg6, object arg7, object arg8, object arg9, object arg10, object arg11, object arg12, object arg13, object arg14, object arg15, object arg16, object arg17, object arg18, object arg19, object arg20, object arg21, object arg22) => throw new WrongNumberOfArgumentsException(1, 23);

            public override object Invoke(object arg0, object arg1, object arg2, object arg3, object arg4, object arg5, object arg6, object arg7, object arg8, object arg9, object arg10, object arg11, object arg12, object arg13, object arg14, object arg15, object arg16, object arg17, object arg18, object arg19, object arg20, object arg21, object arg22, object arg23) => throw new WrongNumberOfArgumentsException(1, 24);

            public override object Invoke(object arg0, object arg1, object arg2, object arg3, object arg4, object arg5, object arg6, object arg7, object arg8, object arg9, object arg10, object arg11, object arg12, object arg13, object arg14, object arg15, object arg16, object arg17, object arg18, object arg19, object arg20, object arg21, object arg22, object arg23, object arg24) => throw new WrongNumberOfArgumentsException(1, 25);

            public override object Invoke(object arg0, object arg1, object arg2, object arg3, object arg4, object arg5, object arg6, object arg7, object arg8, object arg9, object arg10, object arg11, object arg12, object arg13, object arg14, object arg15, object arg16, object arg17, object arg18, object arg19, object arg20, object arg21, object arg22, object arg23, object arg24, object arg25) => throw new WrongNumberOfArgumentsException(1, 26);

            public override object Invoke(object arg0, object arg1, object arg2, object arg3, object arg4, object arg5, object arg6, object arg7, object arg8, object arg9, object arg10, object arg11, object arg12, object arg13, object arg14, object arg15, object arg16, object arg17, object arg18, object arg19, object arg20, object arg21, object arg22, object arg23, object arg24, object arg25, object arg26) => throw new WrongNumberOfArgumentsException(1, 27);

            public override object Invoke(object arg0, object arg1, object arg2, object arg3, object arg4, object arg5, object arg6, object arg7, object arg8, object arg9, object arg10, object arg11, object arg12, object arg13, object arg14, object arg15, object arg16, object arg17, object arg18, object arg19, object arg20, object arg21, object arg22, object arg23, object arg24, object arg25, object arg26, object arg27) => throw new WrongNumberOfArgumentsException(1, 28);

            public override object Invoke(object arg0, object arg1, object arg2, object arg3, object arg4, object arg5, object arg6, object arg7, object arg8, object arg9, object arg10, object arg11, object arg12, object arg13, object arg14, object arg15, object arg16, object arg17, object arg18, object arg19, object arg20, object arg21, object arg22, object arg23, object arg24, object arg25, object arg26, object arg27, object arg28) => throw new WrongNumberOfArgumentsException(1, 29);

            public override object Invoke(object arg0, object arg1, object arg2, object arg3, object arg4, object arg5, object arg6, object arg7, object arg8, object arg9, object arg10, object arg11, object arg12, object arg13, object arg14, object arg15, object arg16, object arg17, object arg18, object arg19, object arg20, object arg21, object arg22, object arg23, object arg24, object arg25, object arg26, object arg27, object arg28, object arg29) => throw new WrongNumberOfArgumentsException(1, 30);

            public override object Invoke(object arg0, object arg1, object arg2, object arg3, object arg4, object arg5, object arg6, object arg7, object arg8, object arg9, object arg10, object arg11, object arg12, object arg13, object arg14, object arg15, object arg16, object arg17, object arg18, object arg19, object arg20, object arg21, object arg22, object arg23, object arg24, object arg25, object arg26, object arg27, object arg28, object arg29, object arg30) => throw new WrongNumberOfArgumentsException(1, 31);

            public override object Invoke(object arg0, object arg1, object arg2, object arg3, object arg4, object arg5, object arg6, object arg7, object arg8, object arg9, object arg10, object arg11, object arg12, object arg13, object arg14, object arg15, object arg16, object arg17, object arg18, object arg19, object arg20, object arg21, object arg22, object arg23, object arg24, object arg25, object arg26, object arg27, object arg28, object arg29, object arg30, object arg31) => throw new WrongNumberOfArgumentsException(1, 32);
        }

        [Fact]
        public void Closure_InvokeWithWrongArguments_ThrowsWrongNumberOfArgumentsException()
        {
            Closure closure = new GeneratedClosureMock();

            // Correct number of arguments doesn't throw
            var result = closure.Invoke("test");
            Assert.Equal("test", result);

            // Too few arguments throws
            var ex1 = Assert.Throws<WrongNumberOfArgumentsException>(() => closure.Invoke());
            Assert.Equal(1, ex1.Expected);
            Assert.Equal(0, ex1.Provided);

            // Too many arguments throws
            var ex2 = Assert.Throws<WrongNumberOfArgumentsException>(() => closure.Invoke("arg1", "arg2"));
            Assert.Equal(1, ex2.Expected);
            Assert.Equal(2, ex2.Provided);
        }
    }
}
