(in-package "CL-USER")

(defparameter *char-map*
  '((#\! "Bng") (#\" "Qut2") (#\# "Shrp") (#\$ "Dllr") (#\% "Pct")
    (#\& "Ampr") (#\' "Qut1") (#\( "Lpar") (#\) "Rpar") (#\* "Str")
    (#\+ "Pls")  (#\, "Cmma") (#\- "Mns")  (#\. "Prd")  (#\/ "Slsh")
    (#\: "Cln")  (#\; "Smicln") (#\< "Lss") (#\= "Equl") (#\> "Grt")
    (#\? "Qst")  (#\@ "Atsgn") (#\[ "Lbrk") (#\\ "Bslsh") (#\] "Rbrk")
    (#\^ "Uparw") (#\_ "Undr") (#\` "Bquot") (#\{ "Lbrc") (#\| "Vbar")
    (#\} "Rbrc") (#\~ "Tld")))

(defun get-code (char) (second (assoc char *char-map*)))
(defun get-char (code) (first (find code *char-map* :key #'second :test #'string-equal)))

(defun title-case (str)
  (if (string= str "") ""
      (concatenate 'string (string-upcase (subseq str 0 1)) (string-downcase (subseq str 1)))))

(defun encode (symbol)
  (let* ((name (string symbol))
         (len (length name))
         (syllables '()))
    (let ((i 0))
      (loop while (< i len)
            do (let ((char (char name i)))
                 (cond
                   ((and (char= char #\-)
                         (plusp i) (< (1+ i) len)
                         (alpha-char-p (char name (1- i)))
                         (alpha-char-p (char name (1+ i))))
                    (incf i))
                   ((alphanumericp char)
                    (let ((start i))
                      (loop while (and (< i len) (alphanumericp (char name i)))
                            do (incf i))
                      (let ((text (subseq name start i)))
                        (push (cond
                                ((or (get-char text)
                                     (digit-char-p (char text 0))
                                     (and (>= (length text) 2) (string-equal (subseq text 0 2) "QQ")))
                                 (concatenate 'string "QQ" (title-case text)))
                                (t (title-case text)))
                              syllables))))
                   (t
                    (incf i)
                    (let ((code (get-code char)))
                      (if code (push code syllables)
                          (error "Unknown char: ~A" char))))))))
    (format nil "~{~A~}" (nreverse syllables))))

(defun write-symbols ()
  (with-open-file (stream (merge-pathnames 
                           (make-pathname :directory '(:relative "CLSymbols")
                                          :name "CL" :type "il")
                           (asdf:system-source-file "clrhack"))
                          :direction :output
                          :if-exists :supersede)
    (format stream ".assembly extern mscorlib { .publickeytoken = (B7 7A 5C 56 19 34 E0 89 ) .ver 4:0:0:0 }~%")
    (format stream ".assembly extern LispBase { .ver 1:0:0:0 }~%")
    (format stream ".assembly extern LispCore { .ver 1:0:0:0 }~%")
    (format stream ".assembly CLSymbols { .ver 1:0:0:0 }~%")
    (format stream ".module CLSymbols.dll~%~%")

    (format stream ".class public abstract auto ansi sealed beforefieldinit Lisp.CL~%")
    (format stream "       extends [mscorlib]System.Object~%")
    (format stream "{~%")
    (do-external-symbols (sym (find-package "CL"))
      (format stream "  .field public static class [LispBase]Lisp.Symbol '_~a'~%" (encode sym)))
    (do-external-symbols (sym (find-package "CL"))
      (format stream "~&~%.method public hidebysig specialname static object 'get_~a' () cil managed~%" (encode sym))
      (format stream "~&{~%")
      (format stream "~&  .maxstack 1")
      (format stream "~&  ldsfld class [LispBase]Lisp.Symbol Lisp.CL::'_~a'~%" (encode sym))
      (format stream "~&  tail. callvirt instance object [LispBase]Lisp.Symbol::get_Value()~%")
      (format stream "~%  ret~%")
      (format stream "~&}~%")

      (format stream "~&~%.method public hidebysig specialname static void 'set_~a'(object 'value') cil managed~%" (encode sym))
      (format stream "~&{~%")
      (format stream "~&  .maxstack 2")
      (format stream "~&  ldsfld class [LispBase]Lisp.Symbol Lisp.CL::'_~a'~%" (encode sym))
      (format stream "~&  ldarg.0~%")
      (format stream "~&  tail. callvirt instance void [LispBase]Lisp.Symbol::set_Value(object)~%")
      (format stream "~%  ret~%")
      (format stream "~&}~%")
      (format stream "  .property object '~a'()~%" (encode sym))
      (format stream "  {~%")
      (format stream "    .get object Lisp.CL::'get_~a'()~%" (encode sym))
      (format stream "    .set void Lisp.CL::'set_~a'(object)~%" (encode sym))
      (format stream "  }~%"))

    (format stream "~%  // =============================================================~%")
    (format stream "  // The Static Class Constructor~%")
    (format stream "  // =============================================================~%")
    (format stream "  .method private specialname rtspecialname static void .cctor() cil managed~%")
    (format stream "  {~%")
    (format stream "    .maxstack 8~%")
    
    (let ((symbols ()))
      (do-external-symbols (sym (find-package "CL"))
        (push sym symbols))
      (setf symbols (sort symbols #'string< :key #'symbol-name))
      (dolist (sym symbols)
        (let ((encoded (encode sym)))
          (format stream "    ldsfld class [LispBase]Lisp.Package [LispBase]Lisp.Package::CommonLisp~%")
          (format stream "    ldstr \"~a\"~%" (symbol-name sym))
          (format stream "    callvirt instance class [LispBase]Lisp.Symbol [LispBase]Lisp.Package::Intern(string)~%")
          (format stream "    stsfld class [LispBase]Lisp.Symbol Lisp.CL::'_~a'~%" encoded)
          (format stream "    ldsfld class [LispBase]Lisp.Package [LispBase]Lisp.Package::CommonLisp~%")
          (format stream "    ldsfld class [LispBase]Lisp.Symbol Lisp.CL::'_~a'~%" encoded)
          (format stream "    callvirt instance void [LispBase]Lisp.Package::Export(class [LispBase]Lisp.Symbol)~%"))))
    
    (format stream "    ldsfld class [LispBase]Lisp.Symbol Lisp.CL::'_Nil'~%")
    (format stream "    call void Lisp.CL::'set_Nil'(object)~%")
    
    (format stream "    ldsfld class [LispBase]Lisp.Symbol Lisp.CL::'_T'~%")
    (format stream "    call void Lisp.CL::'set_T'(object)~%")
    
    (format stream "    call valuetype [LispBase]Lisp.List [LispBase]Lisp.List::get_Empty()~%")
    (format stream "    box [LispBase]Lisp.List~%")
    (format stream "    call void Lisp.CL::'set_StrFeaturesStr'(object)~%")
    
    (format stream "    ldc.i4.s 10~%")
    (format stream "    box [mscorlib]System.Int32~%")
    (format stream "    call void Lisp.CL::'set_StrReadBaseStr'(object)~%")
    
    (format stream "    ldsfld class [LispBase]Lisp.Symbol Lisp.CL::'_Nil'~%")
    (format stream "    call void Lisp.CL::'set_StrReadSuppressStr'(object)~%")
    
    (format stream "    ldsfld class [LispBase]Lisp.Symbol Lisp.CL::'_Nil'~%")
    (format stream "    call void Lisp.CL::'set_StrPrintLengthStr'(object)~%")
    
    (format stream "    ldsfld class [LispBase]Lisp.Symbol Lisp.CL::'_Nil'~%")
    (format stream "    call void Lisp.CL::'set_StrPrintLevelStr'(object)~%")
    
    (format stream "    call class [LispCore]Lisp.Readtable [LispCore]Lisp.Readtable::get_StandardReadtable()~%")
    (format stream "    call void Lisp.CL::'set_StrReadtableStr'(object)~%")

    (format stream "    ret~%")
    (format stream "  }~%")
    
    (format stream "}~%")))
